services:
  rivalz-node:
    build: .
    container_name: rivalz-node
    env_file: .env
    environment:
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - CPU_CORES=${CPU_CORES}
      - RAM=${RAM}
      - DISK_SIZE=${DISK_SIZE}
      - DISK_SELECTION=${DISK_SELECTION}
    restart: unless-stopped
    volumes:
      - rivalz_data:/root/.db
      - rivalz_config:/root/.rivalz

volumes:
  rivalz_data:
  rivalz_config:
